"""empty message

Revision ID: 1086b92511b4
Revises: 31a9c8e3c4cd
Create Date: 2024-08-25 16:22:36.375856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1086b92511b4'
down_revision = '31a9c8e3c4cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('liked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_likes_review_id_reviews')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_likes_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_conversation_user1_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_conversation_user2_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_conversation_sender_id_users'), 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_conversation_recipient_id_users'), 'users', ['recipient_id'], ['id'])
        batch_op.drop_column('user2_id')
        batch_op.drop_column('user1_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_messages_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_messages_sender_id_users'), 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_messages_recipient_id_users'), 'users', ['recipient_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('likes')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_messages_recipient_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_messages_sender_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_messages_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('sender_id')

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user1_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('user2_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_conversation_recipient_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_conversation_sender_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_conversation_user2_id_users', 'users', ['user2_id'], ['id'])
        batch_op.create_foreign_key('fk_conversation_user1_id_users', 'users', ['user1_id'], ['id'])
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('sender_id')

    op.drop_table('likes')
    # ### end Alembic commands ###
