"""empty message

Revision ID: 1b9b10989d32
Revises: e0bd86a7c226
Create Date: 2024-08-27 08:55:04.877840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9b10989d32'
down_revision = 'e0bd86a7c226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('following_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_follows_followed_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_follows_following_id_users'), 'users', ['following_id'], ['id'])
        batch_op.drop_column('followed_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_follows_following_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_follows_followed_id_users', 'users', ['followed_id'], ['id'])
        batch_op.drop_column('following_id')

    # ### end Alembic commands ###
