"""Add likes column to Review model

Revision ID: 48664ae89e96
Revises: db4745c436eb
Create Date: 2024-07-10 10:07:49.098713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48664ae89e96'
down_revision = 'db4745c436eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
