"""empty message

Revision ID: 5d3fa9ebed32
Revises: 60f669432ace
Create Date: 2024-08-30 17:14:54.789207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d3fa9ebed32'
down_revision = '60f669432ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_user_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('follow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follow_id'], ['follows.id'], name=op.f('fk_follow_user_association_follow_id_follows')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_follow_user_association_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'follow_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow_user_association')
    # ### end Alembic commands ###
