"""review update.

Revision ID: b6f4a2471bc7
Revises: 492ef8792527
Create Date: 2024-07-08 17:09:32.627593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f4a2471bc7'
down_revision = '492ef8792527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('user_image', sa.String(length=500), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_reviews_user_image_users'), 'users', ['user_image'], ['image'])
        batch_op.create_foreign_key(batch_op.f('fk_reviews_user_username_users'), 'users', ['user_username'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_user_username_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_user_image_users'), type_='foreignkey')
        batch_op.drop_column('user_image')
        batch_op.drop_column('user_username')

    # ### end Alembic commands ###
