"""empty message

Revision ID: e0bd86a7c226
Revises: 82f25e7b59f5
Create Date: 2024-08-27 08:52:21.723692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0bd86a7c226'
down_revision = '82f25e7b59f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_follows_following_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_follows_followed_id_users'), 'users', ['followed_id'], ['id'])
        batch_op.drop_column('timestamp')
        batch_op.drop_column('following_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('following_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_follows_followed_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_follows_following_id_users', 'users', ['following_id'], ['id'])
        batch_op.drop_column('followed_id')

    # ### end Alembic commands ###
