"""empty message

Revision ID: e32f38a04977
Revises: 5d3fa9ebed32
Create Date: 2024-08-30 19:09:14.864477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e32f38a04977'
down_revision = '5d3fa9ebed32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_user_association', schema=None) as batch_op:
        batch_op.drop_constraint('fk_follow_user_association_follow_id_follows', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_follow_user_association_follow_id_users'), 'users', ['follow_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_user_association', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_follow_user_association_follow_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_follow_user_association_follow_id_follows', 'follows', ['follow_id'], ['id'])

    # ### end Alembic commands ###
